import os
import sys

# known platforms
platforms = {
            'mac': ['darwin', 'os2', 'os2emx', 'riscos', 'atheos'],
            'windows': ['win32', 'cygwin'],
            'linux': ['linux2']
            }

# temporary files (filename, brief description)
# 'ingro': ('input.gro', 'md input .gro file'),
# 'tmpgro': ('tmp.gro', 'md temporary input .gro file'),
# 'allgro': ('confall.gro', '.gro file containing all the configs saved during md'),
# 'allw': ('confall.w', '.w file containing the weights saved during md'),
# 'allev': ('confall.ev', 'file containing the dcs saved during md'),
# 'lsdmgroaa': ('lsdmap_aa.gro', 'file containing the configs used for lsdmap (all atoms)'),
# 'lsdmgro': ('lsdmap.gro', 'file containing the configs used for lsdmap (heavy atoms)'),
# 'lsdmw': ('lsdmap.w', 'file containing the weights used for lsdmap'),
# 'lsdmev': ('lsdmap.ev', 'file containing the eigenvectors generated by lsdmap'),
# 'lsdmeg': ('lsdmap.eg', 'file containing the eigenvalues generated by lsdmap'),
# 'lsdmlog': ('lsdmap.log', 'lsdmap log file'),
# 'fitgroaa': ('fit_aa.gro', '.gro file to fit dcs (all atoms)'),
# 'fitgro': ('fit.gro', '.gro file to fit dcs (heavy atoms)'),
# 'fitev': ('fit.ev', '.ev file containing the dc values of the fitting points'),
# 'fitw': ('fit.w', '.w file to fit dcs'),
# 'fitsig': ('fit.sig', '.sig file to fit dcs'),
# 'embedgro': ('embed.gro', '.gro file containing the configs to be embedded (heavy atoms)'), 
# 'embedev': ('embed.ev', '.ev file containing the dcs of the embedded points'), 
# 'fehist': ('hist.dat', 'file containing free energy histogram data'),
# 'febins': ('bins.xyz', 'file containing coordinates of free energy histograms bins'),
# 'autocorrev': ('autocorr.ev', '.ev file containing enough dcs to compute the autocorrelation time'),
# 'outgro' : ('output.gro', 'temporary .gro file created at the end of dmaps iteration'),
# 'outev' : ('output.ev', '.ev file created at the end of dmaps iteration'),


# known pre executables for radical pilot
stampede_pre_exec = ["module load -intel intel/14.0.1.106", "module load python",
"PYTHONPATH=$PYTHONPATH:/opt/apps/intel14/mvapich2_2_0/python/2.7.6/lib/python2.7",
"PYTHONPATH=$PYTHONPATH:/opt/apps/intel14/mvapich2_2_0/python/2.7.6/lib/python2.7/site-packages",
"PYTHONPATH=$PYTHONPATH:$HOME/.local/lib/python2.7/site-packages","export PYTHONPATH"]

davinci_pre_exec = []
biou_pre_exec = []
localhost_pre_exec = []

known_pre_exec = {"stampede.tacc.utexas.edu": stampede_pre_exec, "rice.davinci": davinci_pre_exec, "rice.biou": biou_pre_exec, "localhost": localhost_pre_exec}

# known parameters (parameter name, section name, tag name)
known_prms = {'ndcs': ('ndcs', 'DMAPS', 'columns'), 'nfit': ('npoints', 'FITTING', 'configs')}
